themanaworld/tmwa

.travis.yml, src/warnings.hpp
Hopefully this works this time.
=> Fix clang builds

src/map/script-fun.cpp
* getitemink("MaggotSlime");
* returns Item link in Manaplus format [@@ID|JName@@]
=> Script Builtin getitemlink

src/map/script-fun.cpp
for use with https://www.themanaworld.org/index.php/User:Meko/Tiled/NPC_Proposal
- - -
closes #38
=> add npc-related builtins

src/map/atcommand.cpp, src/map/magic-stmt.cpp, src/map/map.hpp, src/map/pc.cpp, src/map/pc.hpp, src/map/script-fun.cpp, tools/config.py
Only Death clears killer & killable
Move killer & killable to status namespace
closes #30
=> Make killer & killable script builtins

src/map/pc.cpp
It was so fucking simple.
<sub>\*goes commit seppuku in a corner\*</sub>
=> add OnPCLoginEvent

src/map/atcommand.cpp
Allows to warp to any npc. Works exactly like `@goto` but for npcs
<hr/>
goes with https://github.com/themanaworld/tmwa-server-data/pull/339
=> add @npc atcommand

src/map/chrif.cpp, src/map/script-fun.cpp
Are these messages hard-coded anywhere? I'd hate to break someone's script, but I think that most of the edits are beneficial.
=> Some grammar/spelling/meaning edits for server messages.

src/map/clif.cpp, tools/protocol.py
Hopefully this gets rid of mob position desyncs.
=> Send test 0x0225 packet with servers mob walkpath.

src/map/script-call.cpp, src/map/script-fun.cpp, src/map/script-parse.cpp
Those things have been "deprecated" for so long that now, for sure, no one uses them. This PR makes tmwa puke on anything that would normally get silently ignored.
=> make the script engine scricter

src/ast/item.cpp, src/ast/item.hpp, src/ast/item_test.cpp, src/map/atcommand.cpp, src/map/itemdb.cpp, src/map/itemdb.hpp, src/map/script-fun.cpp
=> remove item labels

src/login/login.cpp, tools/config.py
This needs to be merged asap because if prevents the server from starting if you use the default config
=> remove leftovers from gm atcommand removal

src/map/clif.cpp
oops, I did it the wrong way
anyway, this one works
=> invert mob hp

src/map/clif.cpp, src/map/clif.hpp, src/map/map.hpp, src/map/mapflag.cpp, src/map/mapflag.hpp, src/map/mapflag.py, src/map/npc-parse.cpp, src/map/pc.cpp, src/map/script-fun.cpp, tools/protocol.py
=> npc actions

src/char/char.cpp, tools/config.py
closes https://github.com/themanaworld/tmwa/issues/120
closes https://github.com/themanaworld/tmwa/issues/121
=> char server bug fix & enhancement

src/io/fd.cpp, src/io/fd.hpp, src/net/socket.cpp
As seen in core.cpp tmwa is [already supposed to ignore SIGPIPE](https://github.com/themanaworld/tmwa/blob/master/src/high/core.cpp#L145) but it doesn't do so
http://stackoverflow.com/a/6824284
http://stackoverflow.com/a/1705705
=> replace socket write with send with MSG_NOSIGNAL

src/map/clif.cpp, src/mmo/version.hpp
closes https://github.com/themanaworld/tmwa/pull/129
-  - -
sigh. all this time I though the server had a problem with the walk path but it was in fact so simple
=> Stop sending 0x007b to new clients for mob movement REDUX

src/map/mob.cpp
=> Add missing checks

.travis.yml
=> update travis for new llvm

src/map/script-call-internal.hpp, src/map/script-fun.cpp, src/map/script-parse.cpp
cherry-picked from magic-v3
closes #42
closes #40
closes #136
closes #138
=> some cherry-picked elements from magic-v3

src/map/map.hpp, src/map/mob.cpp
=> Fix how attacked summons behave when master leaves

src/ast/npc.cpp, src/ast/npc_test.cpp, src/map/npc-parse.cpp
requires https://github.com/themanaworld/tmwa-server-data/pull/436
requires https://github.com/themanaworld/tmw-tools/pull/19
=> do not require a name for warps

src/map/battle.cpp, src/map/battle.hpp, src/map/clif.cpp
=> add player nicks back to messages

src/map/clif.cpp
even when the client doesn't send it to the server
=> always send nick to self

src/map/script-fun.cpp
closes https://github.com/themanaworld/tmwa/issues/209
=> override modifications

src/map/pc.cpp, src/map/script-fun.cpp
it's gonna go away maybe next release anyway
closes https://github.com/themanaworld/tmwa-server-data/pull/490
=> revert attachrid modification

src/map/clif.cpp, src/map/map.hpp, src/map/pc.cpp, src/mmo/clif.t.hpp
closes https://github.com/themanaworld/tmwa/issues/208
=> add MUTE params

src/map/battle.cpp, src/map/clif.cpp, src/map/script-fun.cpp
=> Npctalk modifications

src/map/clif.cpp, src/map/clif.hpp, src/map/script-fun.cpp, tools/protocol.py
see https://github.com/ManaPlus/ManaPlus/blob/master/src/enums/resources/map/blocktype.h
=> Implement SMSG_MAP_SET_TILES_TYPE
