- src/map/tmw.cpp
I was puzzled to see that such an important message was silently sent to the Debug tab.
This PR makes the message go to the General tab and appear in bold red
> Send spam messages to General tab

- src/map/script-fun.cpp
ManaPlus uses emotes above 100: https://github.com/ManaPlus/ManaPlus/blob/master/data/graphics/sprites/manaplus_emotes.xml
It was the case since at least 2011 but hasn't been fixed yet.
This PR allows npcs to use the full set of emotes.
- - -
sorry for the previous PR, was on master
> add support for manaplus emotes

- src/map/npc.cpp
- src/map/npc.hpp
- src/map/script-fun.cpp
cmdothernpc has been [deprecated on January 14th](https://github.com/themanaworld/tmwa-server-data/pull/247).
This PR removes it from existence
> remove deprecated cmdothernpc

- src/map/script-fun.cpp
killmonsterall has been [deprecated on January 26th](https://github.com/themanaworld/tmwa-server-data/pull/266)
killmonster should be used instead
> remove deprecated killmonsterall

- src/map/magic-stmt.cpp
This is not the exp bug, it's another bug. Basically it only made it return 0 if the caster is not a PC
> fix bad condition

- src/map/script-call.cpp
I discovered a bug with freeloop. Basically it was always on unless you explicitly do `freeloop 0;` on server start.
> make freeloop check the value

- src/map/npc-parse.cpp
this PR allows to set NOPVP (now used by the pvp channel system) without setting the server to pk mode
> Do not require pk_mode for NOPVP

- src/map/clif.cpp
- src/map/clif.hpp
- src/map/script-fun.cpp
```emotion x;``` display on the npc and send to all
```emotion x, strcharinfo(0);``` display on the npc and send to the specified player
```emotion x, "self";``` display on the attached rid and send to all 
- - -
> make emotion send to a single rid

- src/map/chrif.cpp
- src/map/pc.cpp
- src/map/script-fun.cpp
Sex can now be sent the same way as classes (without kicking the player). No idea why this wasn't done before.. my guess is that perhaps Mana didn't have a packet to update char data.
- - -
> change sex without disconnecting

- src/map/script-fun.cpp
This PR is to deprecate the gmcommand builtin.
It is [still used](https://github.com/themanaworld/tmwa-server-data/search?utf8=%E2%9C%93&q=gmcommand) for ```@l``` , ```@wgm``` , ```@alive``` , ```@killer``` , ```@killable``` and ```@blvl```
- - - 
the plan is:
:white_square_button: [deprecate killer and killable](https://github.com/themanaworld/tmwa/pull/41)
:white_square_button: make wgm into a builtin
:white_square_button: make log into a builtin
:white_square_button: [make ```heal``` automatically resurrect when hp is 0](https://github.com/themanaworld/tmwa/pull/50)
:white_square_button: [make scripts use wgm and gmlog builtins](https://github.com/themanaworld/tmwa-server-data/pull/323) & [fix fightclub](https://github.com/themanaworld/tmwa-server-data/pull/329)
and when all this is …
> deprecate gmcommand builtin

- src/map/pc.cpp
- src/map/script-fun.cpp
First of all, this PR deprecates the ```readparam``` builtin because it is integrated into the ```get_val``` (internal) builtin. This means that if const.txt in server-data is set properly you can directly get properties like ```Int``` without the need for readparam.
- - -
Secondly, I have made the ```set``` builtin do the same thing as ```statusup2``` when using params (does not affect normal variables).
This means that you can do things like ```set Str, Str - 9;``` and it will work as you would expect it to.
- - - 
***Note:*** The params are in the form ```Val``` but for bonus you need to use the form ```bVal```. For example: ```bonus bInt, -Int;```. This is because ```bVal``` is an integer but ```Val``` is a param (so it returns the value). Therefore ```bVit``` always equals 15 but …
> deprecate builtin readparam & statusup2

- src/ast/npc.cpp
- src/ast/npc.hpp
- src/ast/npc_test.cpp
- src/map/clif.cpp
- src/map/npc-parse.cpp
- src/map/npc.cpp
* remove `-|script|name|-1` and make it `-|script|name|32767`
* remove `map,x,y|script|name|-1` completely, `map,x,y|script|name|32767` should be used instead
> npc -1 => 32767

- src/map/chrif.cpp
I removed `OnCharIfInit` because it was a duplicate of the event `OnInterIfInit` (nothing in between the 2 events)
<hr/>
At first, I thought `OnInterIfInit` came before `OnInit` but I was wrong; it is executed after the map server connects to the char server so it's after `OnInit`. Why would you EVER need to wait for char server to do operations that do not require an attached rid? We don't use it and not even hercules found a use for it so I removed it.
> Remove useless events

- src/map/pc.cpp
- src/map/pc.hpp
- src/map/script-fun.cpp
"Save" and "SavePoint" is useless because of ```getsavepoint```
- - -
"Random" is useless because ```warp getmap(), 0, 0;``` does the same thing.
> remove special warp names

- src/map/atcommand.cpp
- src/map/chrif.cpp
- src/map/clif.cpp
- src/map/intif.cpp
- src/map/map.cpp
- src/map/pc.cpp
- tools/config.py
The player is only added to the map block list after the client sends `0x007d` so since the player is not in the list yet it is not sent to other players but it appears in the list and you can `@hugo` and `@goto` to them.
When the client connects to the server it sets `connect_new` to 0 and `auth` to 0. Then it waits for the client to authenticate and sets them both to 1. Finally, the first time the client loads a map it sets `connect_new` to 0. When `connect_new` is 0 and `auth` is 1 we can finally say the player is connected.
I also moved onlogin to after the motd because if we want onlogin to send messages to the player and not only set vars we should wait for the client to be ready.
> wait for the player to be added to block list

- src/map/map.cpp
This allows multiple map servers per char server to split the world between them. 
The only feature tested is that switching between map servers occurs without crashing.
> Don't segfault when inserting remote maps into DB.

- src/map/map.cpp
closes https://github.com/themanaworld/tmwa/issues/117
Let's say someone is doing  boss run and a GM does `@hugo` and enters the room before the next round start. This would cause `getmapusers` to also count the GM so it would make it harder for players as the boss room would spawn more mobs since it would expect one more player. (I tested with Celestia)
`getareausers` does not suffer from this problem because it checks `Opt0::HIDE` but `getmapusers` just grabs `m->users`
> do not count hidden players

- src/map/atcommand.cpp
- src/map/clif.cpp
- src/map/clif.hpp
- src/map/magic-stmt.cpp
- src/map/map.hpp
- src/map/pc.cpp
- src/mmo/version.hpp
- tools/protocol.py
* Send the pvp rank (which is just a kill-streak for now) to the client
* Send the pvp channel to the client [so that it can draw in red the players in the same channel as you](https://github.com/ManaPlus/ManaPlus/pull/13)
to-do in this PR:
* ~~send player hp while in pvp (except if the player has a shroud)~~ **nevermind.** manaplus has no decent way to send player hp (there is only a packet to send player hp for parties)
to-do in the future:
* remove or find a use for legacy `pvp_rank` and `pvp_point` which are not global rank but per-map rank and resets on warp and does not work with the channels. We could recycle it for the channel system and remove the legacy pvp rank system (unused).
* spawn players with pvp as mobs (manaplus allows mobs to have clothes)
- - - 
closes …
> Pvp enhancements

- src/char/char.cpp
- src/char/char.hpp
- src/ints/wrap.hpp
- src/login/login.cpp
- src/login/login.hpp
- src/map/chrif.cpp
- src/map/clif.cpp
- src/map/map.hpp
- src/map/pc.cpp
- src/map/pc.hpp
- src/map/script-fun.cpp
- src/mmo/fwd.hpp
- src/mmo/ids.hpp
- src/mmo/ids.py
- src/mmo/version.hpp
- tools/protocol.py
**tmwa**
- add `ClientVersion` class (wrapped `uint32_t`)
- add missing `native_tag` and `network_tag` to `NativeType`
- add client version to `0x2713` and resize the packet
- resize client version in `0x2afd` to use `ClientVersion` (`uint32_t` vs `uint16_t`)
**login server**
- use the actual version field, not the flags field ([will require a tiny modification in MM+guild](https://github.com/themanaworld/manamarket/commit/7ae66e32c9c8c7d7f2f6037b9d5f95280ede13f8))
- actually handle the flags (well, one of them)
- pass client version to char server
**char server**
- ignore client version sent from client
- use the client version that is sent from login server
- pass client version to map server
**map server**
- update `clif_send` to use `ClientVersion`
> consolidate client version handling

- src/map/clif.cpp
- src/map/clif.hpp
- src/map/script-fun.cpp
- tools/protocol.py
The type allows ManaPlus to know what the message is about, without having to guess
|type|meaning|default behaviour|
|:--:|:------|:----------------|
|0|debug information|log in debug tab|
|1|GM message (spam filter, etc)|log in General tab, highlight tab, play a sound|
|2|warning|log in debug tab, highlight tab|
|3|success|log in debug tab, highlight tab|
|4|failure|log in debug tab, highlight tab|
|5|error|log in debug tab, highlight tab|
|6|TMWA legal notice|log in debug tab|
|7|MOTD|log in debug tab|
|8|scheduled message|log in General tab, highlight tab, play a sound|
|9|event (candor, etc)|log in General tab, highlight tab, play a sound|
Default behaviour for all other types: log in debug tab, highlight tab
For all types, the player should be able to configure the destination tab, …
> implement SMSG_SCRIPT_MESSAGE

- src/map/pc.cpp
Right now, players can `#inma` while dead (or use any other spell). It's being abused in Candor and such
> send hp 0 in pc_readparam when PC is dead

- src/map/script-fun.cpp
since we have `foreach` we don't need aggravate to take area and fx parameters
> simplify `aggravate` builtin
